# Generated by Django 4.2.2 on 2023-06-30 11:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeofenceLocations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("geom", django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                (
                    "centroid",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "verbose_name": "Geofence Location",
                "verbose_name_plural": "Geofence Locations",
            },
        ),
        migrations.CreateModel(
            name="LocationPoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "IATA_shortcode",
                    models.CharField(
                        blank=True,
                        help_text="NBO (for JKIA Nairobi)",
                        max_length=3,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "ICAO_shortcode",
                    models.CharField(
                        blank=True,
                        help_text="HKJK for (JOMO Kenyatta)",
                        max_length=4,
                        null=True,
                        unique=True,
                    ),
                ),
                ("radius", models.FloatField(default=5, help_text="km")),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                "verbose_name": "Location Point",
                "verbose_name_plural": "Location Points",
            },
        ),
        migrations.CreateModel(
            name="Obstacles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "obstacle_type",
                    models.CharField(
                        choices=[
                            ("PWL", "Power Lines"),
                            ("TRS", "Trees"),
                            ("BLD", "Building"),
                            ("TWR", "Tower"),
                        ],
                        max_length=4,
                    ),
                ),
                ("height", models.FloatField(help_text="estimated height in meters")),
                (
                    "description",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("geom", django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ("status", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Obstacle",
                "verbose_name_plural": "Obstacles",
            },
        ),
    ]
