# Generated by Django 4.2.2 on 2024-07-15 08:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AirspaceFrequencies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                ("name", models.CharField(max_length=255)),
                ("is_primary", models.BooleanField(default=False)),
                ("public_use", models.BooleanField(default=False)),
                ("icao_code", models.CharField(max_length=255)),
                ("type_number", models.IntegerField()),
            ],
            options={
                "ordering": ["-value"],
            },
        ),
        migrations.CreateModel(
            name="AirspaceLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("geom", django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                (
                    "centroid",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("icao_class", models.IntegerField(blank=True, null=True)),
                ("upper_limit", models.IntegerField(blank=True, null=True)),
                ("upper_limit_unit", models.IntegerField(null=True)),
                ("lower_limit", models.IntegerField(blank=True, null=True)),
                ("lower_limit_unit", models.IntegerField(blank=True, null=True)),
                ("remarks", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Airspace Location",
                "verbose_name_plural": "Airspace Locations",
            },
        ),
    ]
