# Generated by Django 4.2.2 on 2024-07-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0002_airspacefrequencies_airspacelocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airspacelocation",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
