# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-05 09:57
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_geofencelocations_centroid'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationpoints',
            name='geofence_area',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
