# Generated by Django 4.2.2 on 2024-07-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0003_alter_airspacelocation_remarks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airspacelocation",
            name="name",
            field=models.CharField(max_length=120),
        ),
    ]
