# Generated by Django 4.2.2 on 2024-07-19 06:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0004_alter_airspacelocation_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="airspacefrequencies",
            name="icao_code",
        ),
        migrations.CreateModel(
            name="AirportLocations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("icao_code", models.CharField(max_length=10)),
                ("elevation", models.FloatField(default=0.0)),
                ("geom", django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                (
                    "centroid",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("is_private", models.BooleanField(default=False)),
                ("magnetic_declination", models.FloatField(default=0.0)),
                (
                    "airspace_frequencies",
                    models.ManyToManyField(blank=True, to="maps.airspacefrequencies"),
                ),
            ],
            options={
                "verbose_name": "Airport Location",
                "verbose_name_plural": "Airport Locations",
            },
        ),
    ]
