# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-05 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_locationpoints_geofence_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationpoints',
            name='radius',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
    ]
