# Generated by Django 4.2.2 on 2024-07-19 06:50

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0005_remove_airspacefrequencies_icao_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airportlocations",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
