# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-05 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_locationpoints_radius'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationpoints',
            old_name='geofence_area',
            new_name='geom',
        ),
        migrations.AlterField(
            model_name='locationpoints',
            name='radius',
            field=models.FloatField(default=5, help_text='km'),
        ),
    ]
