# Generated by Django 4.2.2 on 2024-07-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0006_alter_airportlocations_geom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airportlocations",
            name="icao_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
