# Generated by Django 4.2.2 on 2024-07-19 07:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0007_alter_airportlocations_icao_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="airportlocations",
            name="geom",
        ),
        migrations.AddField(
            model_name="airportlocations",
            name="boundary",
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
