# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-05 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_auto_20180205_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationpoints',
            name='shortcode',
            field=models.CharField(default='', max_length=3),
        ),
    ]
