# Generated by Django 4.2.2 on 2024-07-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0008_remove_airportlocations_geom_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="airportlocations",
            name="radius",
            field=models.FloatField(default=10),
        ),
    ]
