# Generated by Django 6.0.3 on 2026-03-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_airportlocations_radius'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportlocations',
            name='radius',
            field=models.FloatField(default=10, help_text='km'),
        ),
    ]
