# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-05 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_auto_20180205_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationpoints',
            old_name='shortcode',
            new_name='IATA_shortcode',
        ),
        migrations.AddField(
            model_name='locationpoints',
            name='ICAO_shortcode',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
