# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-05 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_auto_20180205_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationpoints',
            name='IATA_shortcode',
            field=models.CharField(blank=True, help_text='NBO (for JKIA Nairobi)', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='locationpoints',
            name='ICAO_shortcode',
            field=models.CharField(blank=True, help_text='HKJK for JOMO Kenyatta', max_length=4, null=True),
        ),
    ]
