# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-06 08:42
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0012_auto_20180205_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obstacles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obstacle_type', models.CharField(choices=[('PWL', 'Power Lines'), ('TRS', 'Trees'), ('BLD', 'Building'), ('TWR', 'Tower')], max_length=4)),
                ('height', models.FloatField(help_text='estimated height in meters')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='AirportGeofences',
        ),
    ]
