# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-06 09:42
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0014_auto_20180206_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='obstacles',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
