# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-06 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0015_obstacles_centroid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obstacles',
            name='centroid',
        ),
    ]
