# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-06 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0016_remove_obstacles_centroid'),
    ]

    operations = [
        migrations.AddField(
            model_name='obstacles',
            name='description',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='obstacles',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
