# Generated by Django 2.2.16 on 2021-02-13 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0017_auto_20180206_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geofencelocations',
            options={'verbose_name': 'Geofence Location', 'verbose_name_plural': 'Geofence Locations'},
        ),
        migrations.AlterModelOptions(
            name='locationpoints',
            options={'verbose_name': 'Location Point', 'verbose_name_plural': 'Location Points'},
        ),
        migrations.AlterModelOptions(
            name='obstacles',
            options={'verbose_name': 'Obstacle', 'verbose_name_plural': 'Obstacles'},
        ),
    ]
