# Generated by Django 4.2.2 on 2024-05-01 12:51

import applications.validators
import datetime
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rpas", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogsUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=240)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "log",
                    models.FileField(
                        blank=True, null=True, upload_to="mission-planner-logs/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReserveAirspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "log",
                    models.FileField(
                        blank=True, null=True, upload_to="mission-planner-logs/"
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "start_day",
                    models.DateField(
                        default=datetime.date.today,
                        validators=[applications.validators.validate_start_date],
                    ),
                ),
                ("start_time", models.TimeField(help_text="HH:MM:SS")),
                ("end", models.TimeField(help_text="HH:MM:SS")),
                (
                    "mission_type",
                    models.CharField(
                        choices=[
                            ("TRAIN", "Training"),
                            ("MAPP", "Mapping"),
                            ("3DM", "3D Mapping"),
                            ("DELV", "Delivery"),
                            ("INSP", "Inspection"),
                            ("SURV", "Surveillance"),
                            ("REC", "Recreational"),
                            ("OTH", "Other"),
                        ],
                        default="OTH",
                        max_length=5,
                    ),
                ),
                (
                    "application_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "PENDING"), (1, "DENIED"), (2, "APPROVED")],
                        default=0,
                        null=True,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="If Rejected: Reason for Rejecting",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, help_text="Additional Comments, if any ", null=True
                    ),
                ),
                (
                    "centroid",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("expiry", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rpas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rpas.rpas"
                    ),
                ),
            ],
        ),
    ]
