# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-16 17:56
from __future__ import unicode_literals

from django.db import migrations
import django.utils.datetime_safe
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserveairspace',
            name='geom2',
            field=djgeojson.fields.PolygonField(default=django.utils.datetime_safe.datetime.now),
            preserve_default=False,
        ),
    ]
