# Generated by Django 6.0.3 on 2026-03-21 09:19

import datetime
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('organizations', '0001_initial'),
        ('rpas', '0002_rpas_cor_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserveairspace',
            name='mission_type',
            field=models.CharField(choices=[('SPRAY', 'Spraying'), ('SPREAD', 'Spreading'), ('PHOTO', 'Photography'), ('TRAIN', 'Training'), ('MAPP', 'Mapping'), ('DELV', 'Delivery'), ('INSP', 'Inspection'), ('SURV', 'Surveillance'), ('REC', 'Recreational'), ('OTH', 'Other')], default='OTH', max_length=10),
        ),
        migrations.RemoveField(
            model_name='reserveairspace',
            name='rpas',
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pin_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Kisumu March operations', max_length=240)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
        ),
        migrations.AddField(
            model_name='reserveairspace',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.project'),
        ),
        migrations.AddField(
            model_name='reserveairspace',
            name='rpas',
            field=models.ManyToManyField(to='rpas.rpas'),
        ),
    ]
