# Generated by Django 6.0.3 on 2026-03-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_reserveairspace_mission_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='target_bags',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='target_spray_acres',
            field=models.IntegerField(default=0),
        ),
    ]
