# Generated by Django 6.0.3 on 2026-03-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_project_target_bags_project_target_spray_acres'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estimated_ops_budget',
            field=models.FloatField(default=0.0),
        ),
    ]
