# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-23 13:02
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_remove_reserveairspace_geom2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsupload',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
