# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-27 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_reserveairspace_application_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='logsupload',
            name='log',
            field=models.FileField(blank=True, null=True, upload_to='static/logs'),
        ),
    ]
