# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-31 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_auto_20180127_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsupload',
            name='log',
            field=models.FileField(blank=True, null=True, upload_to='mission-planner-logs/'),
        ),
    ]
