# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-03 13:32
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_auto_20180131_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserveairspace',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
