# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-22 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_reserveairspace_centroid'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserveairspace',
            name='expiry',
            field=models.BooleanField(default=False),
        ),
    ]
