# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-24 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_reserveairspace_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserveairspace',
            name='objective',
            field=models.CharField(choices=[('TRAIN', 'Training'), ('MAPP', 'Mapping'), ('3DM', '3D Mapping'), ('DELV', 'Delivery'), ('INSP', 'Inspection'), ('SURV', 'Surveillance'), ('REC', 'Recreational'), ('OTH', 'Other')], default='OTH', max_length=5),
        ),
    ]
