# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-28 09:32
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_reserveairspace_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserveairspace',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
