# Generated by Django 6.0.3 on 2026-03-23 20:52

import administration.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_alter_reserveairspace_mission_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FOOD', 'Food'), ('ACCOMMODATION', 'Accommodation'), ('PDMS', 'PDMs (Per Diems)'), ('FUEL', 'Fuel'), ('KCAA_FEES', 'KCAA Fees'), ('MAINTENANCE', 'Maintenance'), ('TRANSPORT', 'Transport'), ('OTHER', 'Other')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration_days', models.IntegerField(default=1, editable=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('receipt', models.ImageField(blank=True, null=True, upload_to=administration.models.expense_receipt_upload_path)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_expenses', to='applications.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_expenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FieldRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FOOD', 'Food'), ('ACCOMMODATION', 'Accommodation'), ('PDMS', 'PDMs (Per Diems)'), ('FUEL', 'Fuel'), ('KCAA_FEES', 'KCAA Fees'), ('MAINTENANCE', 'Maintenance'), ('TRANSPORT', 'Transport'), ('OTHER', 'Other')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration_days', models.IntegerField(default=1, editable=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_requisitions', to='applications.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_requisitions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
