# Generated by Django 6.0.3 on 2026-03-23 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldrequisition',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_requisitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fieldrequisition',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldrequisition',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50),
        ),
        migrations.AddField(
            model_name='fieldrequisition',
            name='status_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldexpense',
            name='category',
            field=models.CharField(choices=[('PDMS', 'PDMs (Per Diems)'), ('GEN FUEL', 'Generator Fuel'), ('CAR FUEL', 'Car Fuel'), ('OIL', 'Oil'), ('FOOD', 'Food'), ('MAINTENANCE', 'Maintenance'), ('TRANSPORT', 'Transport'), ('ACCOMMODATION', 'Accommodation'), ('KCAA_FEES', 'KCAA Fees'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fieldexpense',
            name='duration_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fieldexpense',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldrequisition',
            name='category',
            field=models.CharField(choices=[('PDMS', 'PDMs (Per Diems)'), ('GEN FUEL', 'Generator Fuel'), ('CAR FUEL', 'Car Fuel'), ('OIL', 'Oil'), ('FOOD', 'Food'), ('MAINTENANCE', 'Maintenance'), ('TRANSPORT', 'Transport'), ('ACCOMMODATION', 'Accommodation'), ('KCAA_FEES', 'KCAA Fees'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fieldrequisition',
            name='duration_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fieldrequisition',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
