# Generated by Django 6.0.3 on 2026-03-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_fieldrequisition_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='fieldrequisition',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
