/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as uasUasindexImport } from './routes/(uas)/uas_index'
import { Route as uasUASUpdateImport } from './routes/(uas)/UASUpdate'
import { Route as uasUASRegisterImport } from './routes/(uas)/UASRegister'
import { Route as uasUASListImport } from './routes/(uas)/UASList'
import { Route as uasUASDetailsImport } from './routes/(uas)/UASDetails'
import { Route as uasUASCreateImport } from './routes/(uas)/UASCreate'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const uasUasindexRoute = uasUasindexImport.update({
  path: '/uas_index',
  getParentRoute: () => rootRoute,
} as any)

const uasUASUpdateRoute = uasUASUpdateImport.update({
  path: '/UASUpdate',
  getParentRoute: () => rootRoute,
} as any)

const uasUASRegisterRoute = uasUASRegisterImport.update({
  path: '/UASRegister',
  getParentRoute: () => rootRoute,
} as any)

const uasUASListRoute = uasUASListImport.update({
  path: '/UASList',
  getParentRoute: () => rootRoute,
} as any)

const uasUASDetailsRoute = uasUASDetailsImport.update({
  path: '/UASDetails',
  getParentRoute: () => rootRoute,
} as any)

const uasUASCreateRoute = uasUASCreateImport.update({
  path: '/UASCreate',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/(uas)/UASCreate': {
      preLoaderRoute: typeof uasUASCreateImport
      parentRoute: typeof rootRoute
    }
    '/(uas)/UASDetails': {
      preLoaderRoute: typeof uasUASDetailsImport
      parentRoute: typeof rootRoute
    }
    '/(uas)/UASList': {
      preLoaderRoute: typeof uasUASListImport
      parentRoute: typeof rootRoute
    }
    '/(uas)/UASRegister': {
      preLoaderRoute: typeof uasUASRegisterImport
      parentRoute: typeof rootRoute
    }
    '/(uas)/UASUpdate': {
      preLoaderRoute: typeof uasUASUpdateImport
      parentRoute: typeof rootRoute
    }
    '/(uas)/uas_index': {
      preLoaderRoute: typeof uasUasindexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AboutLazyRoute,
  uasUASCreateRoute,
  uasUASDetailsRoute,
  uasUASListRoute,
  uasUASRegisterRoute,
  uasUASUpdateRoute,
  uasUasindexRoute,
])

/* prettier-ignore-end */
