"""
Django settings for ANGA_UTM project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from decouple import Csv, config


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)



DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": config("DATABASE_NAME"),
        "USER": config("DATABASE_USER"),
        "PASSWORD": config("DATABASE_PASSWORD"),
        "HOST": "localhost",
        "PORT": "5432",
    }
}

GDAL_LIBRARY_PATH = os.getenv("GDAL_LIBRARY_PATH")
GEOS_LIBRARY_PATH = os.getenv("GEOS_LIBRARY_PATH")


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Nairobi"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

MEDIA_URL = "/media/"

STATIC_URL = "/static/"


DEFAULT_FILE_STORAGE = "storages.backends.s3boto.S3BotoStorage"
STATICFILES_STORAGE = "storages.backends.s3boto.S3BotoStorage"


LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "rpas_list"

CORS_REPLACE_HTTPS_REFERER = True
HOST_SCHEME = "https://"
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_SECONDS = 1000000
SECURE_FRAME_DENY = True


AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
AWS_DEFAULT_ACL = 'public-read'
AWS_S3_CUSTOM_DOMAIN = config(
    "AWS_S3_CUSTOM_DOMAIN", default=f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"
)
AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}


# Enforce S3 URLs in production even if any earlier setting assigned '/static/'.
STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/static/"
MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/media/"

PWA_APP_NAME = "Anga UTM"
PWA_APP_DESCRIPTION = "Keep It Simple, Stupid"
PWA_APP_THEME_COLOR = "#AA0F0F"
PWA_APP_DISPLAY = "standalone"
PWA_APP_START_URL = "/"
PWA_APP_ICONS = [
    {
        "src": f"https://{AWS_S3_CUSTOM_DOMAIN}/static/favicons/android-icon-36x36.png",
        "sizes": "36x36",
    },
    {
        "src": "https://s3.eu-west-2.amazonaws.com/astral-utm-bucket/static/favicons/android-icon-48x48.png",
        "sizes": "48x48",
    },
    {
        "src": f"https://{AWS_S3_CUSTOM_DOMAIN}/static/favicons/android-icon-72x72.png",
        "sizes": "72x72",
    },
    {
        "src": f"https://{AWS_S3_CUSTOM_DOMAIN}/static/favicons/android-icon-96x96.png",
        "sizes": "96x96",
    },
    {
        "src": "https://s3.eu-west-2.amazonaws.com/astral-utm-bucket/static/favicons/android-icon-144x144.png",
        "sizes": "144x144",
    },
    {
        "src": "https://s3.eu-west-2.amazonaws.com/astral-utm-bucket/static/favicons/192x192.png",
        "sizes": "192x192",
    },
    {
        "src": "https://s3.eu-west-2.amazonaws.com/astral-utm-bucket/static/favicons/384x384.png",
        "sizes": "384x384",
    },
    {
        "src": "https://s3.eu-west-2.amazonaws.com/astral-utm-bucket/static/favicons/512x512.png",
        "sizes": "512x512",
    },
]
# PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, "static/pwabuilder-sw.js")
PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, "static/serviceworker.js")


WEBPUSH_SETTINGS = {
    "VAPID_PUBLIC_KEY": config("VAPID_PUBLIC_KEY"),
    "VAPID_PRIVATE_KEY": config("VAPID_PRIVATE_KEY"),
    "VAPID_ADMIN_EMAIL": config("VAPID_ADMIN_EMAIL"),
}


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "console": {"format": "%(name)-12s %(levelname)-8s %(message)s"},
        "file": {"format": "%(asctime)s %(name)-12s %(levelname)-8s %(message)s"},
    },
    "handlers": {
        "console": {"level": "DEBUG", "class": "logging.StreamHandler"},
        "logfile": {
            "level": "DEBUG",
            # "class": "logging.FileHandler",
            'class': 'logging.handlers.RotatingFileHandler',
            "formatter": "file",
            "filename": os.path.join(BASE_DIR, "logs/logfile.log"),
            'backupCount': 10,  # keep at most 10 log files
            'maxBytes': 5242880,  # 5*1024*1024 bytes (5MB)
        },
    },
    "root": {"level": "INFO", "handlers": ["console", "logfile"]},
    "loggers": {"": {"level": "DEBUG", "handlers": ["console", "logfile"]}},
}

CSRF_TRUSTED_ORIGINS = [
    'https://anga.precisiondrones.africa',
    'https://www.anga.precisiondrones.africa',
]

from ANGA_UTM.aws.conf import *

