# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-11 07:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_type', models.CharField(choices=[('ROC', 'ROC'), ('REC', 'RECREATIONAL'), ('PVT', 'PRIVATE'), ('ATO', 'Training Organization')], max_length=3, null=True)),
                ('kcaa_no', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('logo', models.ImageField(blank=True, upload_to='images/logo')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizations.OrganizationDetails'),
        ),
        migrations.AddField(
            model_name='organization',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
