# Generated by Django 4.2.2 on 2024-05-01 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrganizationDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("city", models.CharField(max_length=100)),
                ("website", models.URLField()),
                ("logo", models.ImageField(blank=True, upload_to="images/logo")),
            ],
            options={
                "verbose_name": "Organization Detail",
                "verbose_name_plural": "Organization Details",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization_type",
                    models.CharField(
                        choices=[
                            ("ROC", "ROC"),
                            ("REC", "RECREATIONAL"),
                            ("PVT", "PRIVATE"),
                            ("UTO", "Training Organization"),
                            ("CLB", "RC Club"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("caa_no", models.CharField(max_length=50, unique=True)),
                (
                    "organization_details",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organizationdetails",
                    ),
                ),
            ],
        ),
    ]
