# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-22 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(choices=[('ROC', 'ROC'), ('REC', 'RECREATIONAL'), ('PVT', 'PRIVATE'), ('ATO', 'Training Organization'), ('CLB', 'RC Club')], max_length=3, null=True),
        ),
    ]
