# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-23 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_postholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postholder',
            name='role',
            field=models.CharField(choices=[('Man', 'Manager'), ('PIC', 'Pilot in Command'), ('HOT', 'Head of Training'), ('ORD', 'Ordinary')], max_length=3),
        ),
    ]
