# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-23 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_auto_20180423_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postholder',
            name='role',
            field=models.CharField(choices=[('ORD', 'Ordinary'), ('Man', 'Manager'), ('PIC', 'Pilot in Command'), ('HOT', 'Head of Training'), ('TEC', 'Technical')], default='Manager', max_length=3),
        ),
    ]
