# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-23 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_auto_20180423_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='postholder',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization'),
        ),
    ]
