# Generated by Django 2.2.16 on 2021-02-13 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_auto_20200305_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationdetails',
            options={'verbose_name': 'Organization Detail', 'verbose_name_plural': 'Organization Details'},
        ),
    ]
