# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-04 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utm_messages', '0002_remove_usertousermessages_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertousermessages',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
