# Generated by Django 2.2.16 on 2021-02-13 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utm_messages', '0005_auto_20180503_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertousermessages',
            options={'verbose_name': 'User To User Message', 'verbose_name_plural': 'User To User Messages'},
        ),
    ]
