# Generated by Django 6.0.3 on 2026-03-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='expo_push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('pilot', 'pilot'), ('client', 'client'), ('ops_manager', 'Operations Manager'), ('safety_manager', 'Safety Manager'), ('quality_manager', 'Quality Manager'), ('acc_manager', 'Accountable Manager'), ('sec_manager', 'Security Manager'), ('caa', 'KCAA'), ('mod', 'MOD')], default='pilot', max_length=40),
        ),
    ]
