# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-07 07:35
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+254', help_text='+254....', max_length=128, null=True),
        ),
    ]
