# Generated by Django 4.2.2 on 2024-05-01 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("country", models.CharField(max_length=20)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/logo/manufacturer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payload_serial",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "payload_nickname",
                    models.CharField(
                        blank=True, help_text="if any.....", max_length=20, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayloadModelType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payload_type",
                    models.CharField(
                        choices=[
                            ("RBG", "RGB CAMERA"),
                            ("MSTL", "MULTISPECTRAL"),
                            ("HYPL", "HYPERSPECTRAL"),
                            ("FPV", "FPV"),
                            ("SURV", "SURVIELANCE"),
                            ("VTOL", "VTOL"),
                            ("IFR", "INFRA-RED"),
                        ],
                        max_length=5,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RpasModelType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "airframe_type",
                    models.CharField(
                        choices=[
                            ("PLANE", "PLANE"),
                            ("QUAD", "QUADCOPTER"),
                            ("HEXA", "HEXACOPTER"),
                            ("TRI", "TRICOPTER"),
                            ("OCTA", "OCTACOPTER"),
                            ("VTOL", "VTOL"),
                        ],
                        max_length=5,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RpasModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(blank=True, max_length=20, null=True)),
                ("weight", models.FloatField(blank=True, null=True)),
                (
                    "manufacturer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rpas.manufacturer",
                    ),
                ),
                (
                    "rpas_model_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rpas.rpasmodeltype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rpas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rpas_serial", models.CharField(max_length=20, unique=True)),
                (
                    "rpas_nickname",
                    models.CharField(
                        blank=True,
                        help_text="If any....e.g My Phantom Bird",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("rpas_pic", models.ImageField(upload_to="images/rpas")),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
                (
                    "payload",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rpas.payload",
                    ),
                ),
                (
                    "rpas_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rpas.rpasmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rpas",
                "verbose_name_plural": "Rpas",
            },
        ),
        migrations.CreateModel(
            name="PayloadModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payload_name", models.CharField(max_length=20, unique=True)),
                ("payload_weight", models.CharField(max_length=20)),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rpas.manufacturer",
                    ),
                ),
                (
                    "payload_model_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rpas.payloadmodeltype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="payload",
            name="payload_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rpas.payloadmodel",
            ),
        ),
        migrations.CreateModel(
            name="Battery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batt_name", models.CharField(max_length=20, unique=True)),
                ("batt_volts", models.CharField(max_length=20)),
                ("batt_amps", models.CharField(max_length=20)),
                ("batt_number", models.IntegerField()),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rpas.manufacturer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Battery",
                "verbose_name_plural": "Batteries",
            },
        ),
    ]
