# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-11 07:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batt_name', models.CharField(max_length=20, unique=True)),
                ('batt_volts', models.CharField(max_length=20)),
                ('batt_amps', models.CharField(max_length=20)),
                ('batt_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('country', models.CharField(max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/logo/manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload_serial', models.CharField(max_length=20)),
                ('payload_nickname', models.CharField(max_length=20)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpas.Manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='PayloadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload_name', models.CharField(max_length=20, unique=True)),
                ('payload_weight', models.CharField(max_length=20)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpas.Manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='PayloadModelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload_type', models.CharField(choices=[('RBG', 'RGB CAMERA'), ('MSTL', 'MULTISPECTRAL'), ('HYPL', 'HYPERSPECTRAL'), ('FPV', 'FPV'), ('SURV', 'SURVIELANCE'), ('VTOL', 'VTOL'), ('IFR', 'INFRA-RED')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Rpas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpas_serial', models.CharField(max_length=20)),
                ('rpas_nickname', models.CharField(max_length=20)),
                ('rpas_pic', models.ImageField(upload_to='images/rpas')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization')),
                ('payload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpas.Payload')),
            ],
        ),
        migrations.CreateModel(
            name='RpasModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=20, unique=True)),
                ('weight', models.CharField(max_length=20)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpas.Manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='RpasModelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airframe_type', models.CharField(choices=[('PLANE', 'PLANE'), ('QUAD', 'QUADCOPTER'), ('HEXA', 'HEXACOPTER'), ('TRI', 'TRICOPTER'), ('OCTA', 'OCTACOPTER'), ('VTOL', 'VTOL')], max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='rpasmodel',
            name='rpas_model_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpas.RpasModelType'),
        ),
        migrations.AddField(
            model_name='rpas',
            name='rpas_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpas.RpasModel'),
        ),
        migrations.AddField(
            model_name='rpas',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payloadmodel',
            name='payload_model_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpas.PayloadModelType'),
        ),
        migrations.AddField(
            model_name='payload',
            name='payload_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpas.PayloadModel'),
        ),
        migrations.AddField(
            model_name='battery',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpas.Manufacturer'),
        ),
    ]
