# Generated by Django 6.0.3 on 2026-03-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpas',
            name='cor_number',
            field=models.CharField(blank=True, help_text='Certificate of Registration Number', max_length=50, null=True),
        ),
    ]
