# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-02 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpasmodel',
            name='weight',
            field=models.FloatField(),
        ),
    ]
