# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-02 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpas', '0003_auto_20180402_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpas',
            name='rpas_nickname',
            field=models.CharField(blank=True, help_text='If any....e.g My Phantom Bird', max_length=20, null=True),
        ),
    ]
