# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-09 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpas', '0006_auto_20180405_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payload',
            name='payload_nickname',
            field=models.CharField(blank=True, help_text='if any.....', max_length=20, null=True),
        ),
    ]
