# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-22 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpas', '0007_auto_20180409_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payload',
            name='manufacturer',
        ),
    ]
