# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-05 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpas', '0008_remove_payload_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpas',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization'),
        ),
    ]
