# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-05 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpas', '0009_auto_20180505_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpasmodel',
            name='model_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
