# Generated by Django 2.2.16 on 2021-02-13 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpas', '0010_auto_20180505_2314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='battery',
            options={'verbose_name': 'Battery', 'verbose_name_plural': 'Batteries'},
        ),
        migrations.AlterModelOptions(
            name='rpas',
            options={'verbose_name': 'Rpas', 'verbose_name_plural': 'Rpas'},
        ),
    ]
