# Generated by Django 4.2.2 on 2023-06-30 11:49

import applications.validators
import datetime
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotamAirspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("geom", django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "start_day",
                    models.DateField(
                        default=datetime.date.today,
                        validators=[applications.validators.validate_start_date],
                    ),
                ),
                ("start_time", models.TimeField(help_text="HH:MM:SS")),
                ("end", models.TimeField(help_text="HH:MM:SS")),
                (
                    "notam_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "notam_file",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/%Y/%m/%d/"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "PENDING"), (1, "ACTIVE")],
                        default=0,
                        null=True,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text=" Reason for NOTAM",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "centroid",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("expiry", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
