# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-28 12:35
from __future__ import unicode_literals

import applications.validators
import datetime
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotamAirspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('start_day', models.DateField(default=datetime.date.today, validators=[applications.validators.validate_start_date])),
                ('start_time', models.TimeField(help_text='HH:MM:SS')),
                ('end', models.TimeField(help_text='HH:MM:SS')),
                ('application_number', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(0, 'PENDING'), (1, 'DENIED')], default=0, null=True)),
                ('reason', models.CharField(blank=True, help_text='If Rejected: Reason for Rejecting', max_length=255, null=True)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('expiry', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
