# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-01 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notamairspace',
            old_name='application_number',
            new_name='notam_number',
        ),
    ]
