# Generated by Django 4.2.2 on 2023-06-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("weather", models.CharField(max_length=20)),
                ("wind_str", models.CharField(max_length=100)),
                ("temp", models.IntegerField()),
                ("humidity", models.CharField(max_length=100)),
                ("precip", models.CharField(max_length=100)),
                ("icon_url", models.URLField()),
                ("observation_time", models.CharField(max_length=100)),
            ],
        ),
    ]
