# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-11 08:07
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rpas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_amps', models.DecimalField(decimal_places=1, max_digits=5)),
                ('end_volts', models.CharField(max_length=20)),
                ('batt_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpas.Battery')),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parts_check', models.CharField(max_length=100)),
                ('charge_status', models.CharField(max_length=20)),
                ('props_check', models.CharField(max_length=20)),
                ('firmware_check', models.TextField(max_length=200)),
                ('camera_check', models.CharField(max_length=20)),
                ('risk_assesment', models.CharField(max_length=20)),
                ('conditions_check', models.TextField(max_length=200)),
                ('connection_check', models.TextField(max_length=200)),
                ('rpas_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rpas.RpasModel')),
            ],
        ),
        migrations.CreateModel(
            name='CrewBriefing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_flights', models.IntegerField()),
                ('duties', models.CharField(max_length=20)),
                ('tk_off_area', models.CharField(max_length=20)),
                ('alt_landing_area', models.CharField(max_length=20)),
                ('env_factors', models.TextField(max_length=20)),
                ('air_band_radio', models.CharField(max_length=20)),
                ('notams', models.TextField(max_length=20)),
                ('copy_of_ops_pack', models.BooleanField()),
                ('security', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='EmmergencyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closest_hosp', models.CharField(max_length=100)),
                ('fire_dept', models.CharField(max_length=20)),
                ('nearest_police_stn', models.CharField(max_length=20)),
                ('security_service', models.CharField(max_length=20)),
                ('other', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FlightLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_number', models.CharField(default='2017/11/', help_text='2018/01/23/001', max_length=20, unique=True)),
                ('date', models.DateField(help_text='YYYY-MM-DD')),
                ('emmergency_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_plans.EmmergencyInfo')),
            ],
        ),
        migrations.CreateModel(
            name='MissionLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('map_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='MissionObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.CharField(choices=[('TRAIN', 'Training'), ('MAPP', 'Mapping'), ('3DM', '3D Mapping'), ('DELV', 'Delivery'), ('INSP', 'Inspection'), ('SURV', 'Surveillance')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='MissionPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='MissionWrap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damages', models.CharField(max_length=20)),
                ('comments', models.CharField(max_length=500)),
                ('mission_success', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PreFlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('take_off_time', models.TimeField(blank=True, null=True)),
                ('altitude', models.CharField(max_length=20)),
                ('est_flight_time', models.CharField(max_length=20)),
                ('area_size', models.CharField(max_length=20)),
                ('no_of_flights', models.CharField(default='1', max_length=20)),
                ('other_info', models.CharField(blank=True, max_length=300, null=True)),
                ('batt_reminder', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather', models.CharField(max_length=20)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_plans.MissionLocation')),
            ],
        ),
        migrations.AddField(
            model_name='preflight',
            name='sitesurvey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_plans.SiteSurvey'),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_plans.MissionLocation'),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='missionpath',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_plans.MissionPath'),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='postflight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_plans.MissionWrap'),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='pre_flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_plans.PreFlight'),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='purpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_plans.MissionObjective'),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='rpas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpas.Rpas'),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emmergencyinfo',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_plans.MissionLocation'),
        ),
    ]
