# Generated by Django 4.2.2 on 2024-05-01 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("applications", "0001_initial"),
        ("rpas", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_title", models.CharField(max_length=40)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/checklists/profile_pic"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CrewBriefing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no_of_flights", models.IntegerField()),
                ("duties", models.CharField(max_length=20)),
                ("alt_landing_area", models.CharField(max_length=20)),
                ("env_factors", models.TextField(max_length=20)),
                ("air_band_radio", models.CharField(max_length=20)),
                ("notam_action", models.TextField(default="None", max_length=20)),
                ("copy_of_ops_pack", models.BooleanField()),
                ("security", models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="EmmergencyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("closest_hosp", models.CharField(max_length=100)),
                ("fire_dept", models.CharField(max_length=20)),
                ("nearest_police_stn", models.CharField(max_length=20)),
                ("security_service", models.CharField(max_length=20)),
                ("other", models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="MissionWrap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("damages", models.CharField(blank=True, max_length=20, null=True)),
                ("comments", models.CharField(blank=True, max_length=500, null=True)),
                ("mission_success", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="PreFlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weather", models.CharField(default="", max_length=20)),
                ("altitude", models.CharField(max_length=20)),
                ("est_flight_time", models.CharField(max_length=20)),
                ("no_of_flights", models.CharField(default="1", max_length=20)),
                ("other_info", models.CharField(blank=True, max_length=300, null=True)),
                ("batt_reminder", models.CharField(default="", max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="FlightLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emmergency_info",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flight_plans.emmergencyinfo",
                    ),
                ),
                (
                    "post_flight",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flight_plans.missionwrap",
                    ),
                ),
                (
                    "pre_flight",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flight_plans.preflight",
                    ),
                ),
                (
                    "reserve_airspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.reserveairspace",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChecklistGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "checklist_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PRE", "Pre-Flight"),
                            ("POS", "Post-Flight"),
                            ("INF", "InFlight"),
                            ("EMR", "Emergency"),
                            ("CHR", "Charging"),
                            ("ASM", "Assembly"),
                            ("MNT", "Maintenance"),
                            ("OTH", "Other"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "checklists",
                    models.ManyToManyField(
                        related_name="checklists", to="flight_plans.checklistitem"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Checklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parts_check", models.CharField(max_length=100)),
                ("charge_status", models.CharField(max_length=20)),
                ("props_check", models.CharField(max_length=20)),
                ("firmware_check", models.TextField(max_length=200)),
                ("camera_check", models.CharField(max_length=20)),
                ("risk_assesment", models.CharField(max_length=20)),
                ("conditions_check", models.TextField(max_length=200)),
                ("connection_check", models.TextField(max_length=200)),
                (
                    "rpas_model",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="rpas.rpasmodel"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BatteryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("end_amps", models.DecimalField(decimal_places=1, max_digits=5)),
                ("end_volts", models.CharField(max_length=20)),
                (
                    "batt_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rpas.battery"
                    ),
                ),
            ],
        ),
    ]
