# Generated by Django 6.0.3 on 2026-03-21 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='rpas_model',
        ),
        migrations.RemoveField(
            model_name='checklistitem',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='preflight',
            name='batt_reminder',
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='is_optional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='item_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='checklistgroup',
            name='checklists',
            field=models.ManyToManyField(related_name='checklist_groups', to='flight_plans.checklistitem'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='item_title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='ChecklistSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.JSONField(default=list)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('checklist_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flight_plans.checklistgroup')),
                ('flight_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_submissions', to='flight_plans.flightlog')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('checklist_type', models.CharField(default='', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(related_name='parent_checklists', to='flight_plans.checklistgroup')),
            ],
        ),
        migrations.AddField(
            model_name='missionwrap',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flight_plans.checklisttemplate'),
        ),
        migrations.AddField(
            model_name='preflight',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flight_plans.checklisttemplate'),
        ),
        migrations.DeleteModel(
            name='BatteryLog',
        ),
        migrations.DeleteModel(
            name='Checklist',
        ),
    ]
