# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-17 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_reserveairspace_expiry'),
        ('flight_plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightlog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='flightlog',
            name='location',
        ),
        migrations.RemoveField(
            model_name='flightlog',
            name='missionpath',
        ),
        migrations.RemoveField(
            model_name='flightlog',
            name='rpas',
        ),
        migrations.AddField(
            model_name='flightlog',
            name='approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.ReserveAirspace'),
        ),
        migrations.AlterField(
            model_name='missionobjective',
            name='objective',
            field=models.CharField(choices=[('TRAIN', 'Training'), ('MAPP', 'Mapping'), ('3DM', '3D Mapping'), ('DELV', 'Delivery'), ('INSP', 'Inspection'), ('SURV', 'Surveillance'), ('REC', 'Recreational'), ('OTH', 'Other')], max_length=5),
        ),
    ]
