# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-24 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_plans', '0002_auto_20180317_1524'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MissionPath',
        ),
        migrations.RemoveField(
            model_name='sitesurvey',
            name='location',
        ),
        migrations.RemoveField(
            model_name='emmergencyinfo',
            name='location',
        ),
        migrations.RemoveField(
            model_name='flightlog',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='preflight',
            name='sitesurvey',
        ),
        migrations.AddField(
            model_name='preflight',
            name='weather',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='MissionLocation',
        ),
        migrations.DeleteModel(
            name='MissionObjective',
        ),
        migrations.DeleteModel(
            name='SiteSurvey',
        ),
    ]
