# Generated by Django 6.0.3 on 2026-03-21 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight_plans', '0002_remove_checklist_rpas_model_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrewBriefing',
        ),
        migrations.RemoveField(
            model_name='flightlog',
            name='emmergency_info',
        ),
        migrations.RemoveField(
            model_name='missionwrap',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='missionwrap',
            name='damages',
        ),
        migrations.RemoveField(
            model_name='missionwrap',
            name='mission_success',
        ),
        migrations.RemoveField(
            model_name='preflight',
            name='altitude',
        ),
        migrations.RemoveField(
            model_name='preflight',
            name='est_flight_time',
        ),
        migrations.RemoveField(
            model_name='preflight',
            name='no_of_flights',
        ),
        migrations.RemoveField(
            model_name='preflight',
            name='other_info',
        ),
        migrations.RemoveField(
            model_name='preflight',
            name='weather',
        ),
        migrations.DeleteModel(
            name='EmmergencyInfo',
        ),
    ]
