# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-25 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_plans', '0003_auto_20180324_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightlog',
            old_name='approval',
            new_name='reserve_airspace',
        ),
        migrations.RemoveField(
            model_name='crewbriefing',
            name='notams',
        ),
        migrations.RemoveField(
            model_name='crewbriefing',
            name='tk_off_area',
        ),
        migrations.RemoveField(
            model_name='flightlog',
            name='log_number',
        ),
        migrations.RemoveField(
            model_name='preflight',
            name='take_off_time',
        ),
        migrations.AddField(
            model_name='crewbriefing',
            name='notam_action',
            field=models.TextField(default='None', max_length=20),
        ),
    ]
