# Generated by Django 6.0.3 on 2026-03-21 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_plans', '0003_delete_crewbriefing_remove_flightlog_emmergency_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightlog',
            name='post_flight',
        ),
        migrations.RemoveField(
            model_name='preflight',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='flightlog',
            name='pre_flight',
        ),
        migrations.AddField(
            model_name='flightlog',
            name='postflight_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postflight_logs', to='flight_plans.checklisttemplate'),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='preflight_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preflight_logs', to='flight_plans.checklisttemplate'),
        ),
        migrations.DeleteModel(
            name='MissionWrap',
        ),
        migrations.DeleteModel(
            name='PreFlight',
        ),
    ]
