# Generated by Django 6.0.3 on 2026-03-22 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_plans', '0004_remove_flightlog_post_flight_and_more'),
        ('organizations', '0001_initial'),
        ('rpas', '0002_rpas_cor_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistgroup',
            name='checklists',
        ),
        migrations.RemoveField(
            model_name='checklistsubmission',
            name='checklist_group',
        ),
        migrations.RemoveField(
            model_name='checklisttemplate',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='checklisttemplate',
            name='date_modified',
        ),
        migrations.AddField(
            model_name='checklistsubmission',
            name='checklist_type',
            field=models.CharField(default='PRE', max_length=3),
        ),
        migrations.AddField(
            model_name='checklistsubmission',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='checklistsubmission',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flight_plans.checklisttemplate'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='checklist_data',
            field=models.JSONField(default='{}', help_text='Full template structure in JSON format'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='rpas_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_templates', to='rpas.rpasmodel'),
        ),
        migrations.AlterField(
            model_name='checklistsubmission',
            name='results',
            field=models.JSONField(help_text='Responses for each item with status and comments'),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='checklist_type',
            field=models.CharField(choices=[('PRE', 'Pre-Flight'), ('POS', 'Post-Flight'), ('INF', 'In-Flight'), ('EMR', 'Emergency')], default='PRE', max_length=3),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='postflight_template',
            field=models.ForeignKey(blank=True, limit_choices_to={'checklist_type': 'POS'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postflight_logs', to='flight_plans.checklisttemplate'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='preflight_template',
            field=models.ForeignKey(blank=True, limit_choices_to={'checklist_type': 'PRE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preflight_logs', to='flight_plans.checklisttemplate'),
        ),
        migrations.DeleteModel(
            name='ChecklistItem',
        ),
        migrations.DeleteModel(
            name='ChecklistGroup',
        ),
    ]
