# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-27 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight_plans', '0004_auto_20180325_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightlog',
            name='postflight',
        ),
        migrations.AddField(
            model_name='flightlog',
            name='post_flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flight_plans.MissionWrap'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='emmergency_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flight_plans.EmmergencyInfo'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='pre_flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flight_plans.PreFlight'),
        ),
    ]
