# Generated by Django 6.0.3 on 2026-03-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_plans', '0005_remove_checklistgroup_checklists_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistsubmission',
            name='checklist_type',
            field=models.CharField(default='PRE', max_length=5),
        ),
    ]
