# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-27 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_plans', '0005_auto_20180327_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionwrap',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='missionwrap',
            name='damages',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='missionwrap',
            name='mission_success',
            field=models.BooleanField(default=False),
        ),
    ]
