# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-26 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight_plans', '0006_auto_20180327_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preflight',
            name='area_size',
        ),
    ]
