# Generated by Django 2.2.16 on 2021-02-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_plans', '0007_remove_preflight_area_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=140)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/checklists/profile_pic')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('checklists', models.ManyToManyField(to='flight_plans.ChecklistItem')),
            ],
        ),
    ]
