# Generated by Django 6.0.3 on 2026-03-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_plans', '0007_alter_checklisttemplate_checklist_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistsubmission',
            name='checklist_type',
            field=models.CharField(default='PRE', max_length=20),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='checklist_type',
            field=models.CharField(choices=[('PRE', 'Pre-Flight'), ('POS', 'Post-Flight'), ('INF', 'In-Flight'), ('EMR', 'Emergency')], default='PRE', max_length=20),
        ),
    ]
