# Generated by Django 6.0.3 on 2026-03-22 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_reserveairspace_mission_type_and_more'),
        ('flight_plans', '0008_alter_checklistsubmission_checklist_type_and_more'),
        ('organizations', '0001_initial'),
        ('rpas', '0002_rpas_cor_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acres_sprayed', models.FloatField(default=0.0)),
                ('bags_spread', models.FloatField(default=0.0)),
                ('application_rate_spraying', models.FloatField(default=0.0, help_text='in l/ha')),
                ('operation_date', models.DateField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('postflight_template', models.ForeignKey(blank=True, limit_choices_to={'checklist_type': 'POS'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postflight_work_logs', to='flight_plans.checklisttemplate')),
                ('preflight_template', models.ForeignKey(blank=True, limit_choices_to={'checklist_type': 'PRE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preflight_work_logs', to='flight_plans.checklisttemplate')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.project')),
                ('reserve_airspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.reserveairspace')),
                ('rpas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rpas.rpas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='checklistsubmission',
            name='flight_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_submissions', to='flight_plans.dailyworklog'),
        ),
        migrations.DeleteModel(
            name='FlightLog',
        ),
    ]
