# Generated by Django 6.0.3 on 2026-03-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_plans', '0009_dailyworklog_alter_checklistsubmission_flight_log_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyworklog',
            name='operation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
