# Generated by Django 2.2.16 on 2021-02-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_plans', '0009_auto_20210213_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistgroup',
            name='checklists',
            field=models.ManyToManyField(related_name='checklists', to='flight_plans.ChecklistItem'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
