# Generated by Django 6.0.3 on 2026-03-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_plans', '0010_alter_dailyworklog_operation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyworklog',
            name='operation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
