# Generated by Django 2.2.16 on 2021-02-13 16:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flight_plans', '0010_auto_20210213_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistgroup',
            name='checklist_type',
            field=models.CharField(blank=True, choices=[('PRE', 'Pre-Flight'), ('POS', 'Post-Flight'), ('INF', 'InFlight'), ('EMR', 'Emergency'), ('CHR', 'Charging'), ('ASM', 'Assembly'), ('MNT', 'Maintenance'), ('OTH', 'Other')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='checklistgroup',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklistgroup',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
