# Generated by Django 6.0.3 on 2026-03-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_plans', '0011_alter_dailyworklog_operation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyworklog',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
