# Generated by Django 6.0.3 on 2026-03-22 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight_plans', '0012_dailyworklog_is_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklistsubmission',
            old_name='flight_log',
            new_name='work_log',
        ),
    ]
