# Generated by Django 6.0.3 on 2026-03-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_plans', '0013_rename_flight_log_checklistsubmission_work_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistsubmission',
            name='checklist_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
