# Generated by Django 6.0.3 on 2026-03-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_plans', '0015_dailyworklog_postflight_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyworklog',
            name='estimated_ops_budget',
            field=models.FloatField(default=0.0),
        ),
    ]
