# Generated by Django 6.0.3 on 2026-03-23 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight_plans', '0016_dailyworklog_estimated_ops_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyworklog',
            name='estimated_ops_budget',
        ),
    ]
