# Generated by Django 2.2.16 on 2021-02-13 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifications',
            options={'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
    ]
