"""
This type stub file was generated by pyright.
"""

from __future__ import unicode_literals

""" Mixer is an object generation tool for your application.

It's supported Django_ ORM, SQLAlchemy_ ORM, Pony_ ORM, Peewee_ ORM,
Mongoengine_ ODM and etc.

Mixer is very useful for testing and fixtures replacement.

:copyright: 2013 by Kirill Klenov.
:license: BSD, see LICENSE for more details.

"""
__version__ = "6.1.3"
__project__ = "mixer"
__author__ = "horneds <horneds@gmail.com>"
__license__ = "BSD"
