"""
This type stub file was generated by pyright.
"""

import sys

""" Compatibility layer.

    Some py2/py3 compatibility support based on a stripped down
    version of six so we don't have to depend on a specific version
    of it.

    :copyright: (c) 2014 by Armin Ronacher.
    :license: BSD
"""
PY2 = sys.version_info[0] == 2
_identity = lambda x: x
if not PY2:
    text_type = str
    string_types = (str, )
    integer_types = (int, )
    iterkeys = lambda d: iter(d.keys())
    itervalues = lambda d: iter(d.values())
    iteritems = lambda d: iter(d.items())
    def reraise(tp, value, tb=...):
        ...
    
    implements_to_string = _identity
else:
    text_type = unicode
    string_types = (str, unicode)
    integer_types = (int, long)
    iterkeys = lambda d: d.iterkeys()
    itervalues = lambda d: d.itervalues()
    iteritems = lambda d: d.iteritems()
    def implements_to_string(cls):
        ...
    
def with_metaclass(meta, *bases):
    class metaclass(meta):
        ...
    
    

BROKEN_PYPY_CTXMGR_EXIT = False
if hasattr(sys, 'pypy_version_info'):
    class _Mgr(object):
        def __enter__(self):
            ...
        
        def __exit__(self, *args):
            ...
        
    
    
